import { formatMoney } from '../../shared/utils/presentation';
export interface SummaryValues { income: number; expenses: number; debtPayments: number; savings: number; available: number }
export function DistributionBar({ values }: { values: SummaryValues }) {
  const items = [{ label: 'Gastos', value: values.expenses, color: '#ff646b' }, { label: 'Deudas', value: values.debtPayments, color: '#ffb800' }, { label: 'Ahorro', value: values.savings, color: '#42d580' }, { label: 'Libre', value: values.available, color: '#4b9af7' }];
  const total = items.reduce((sum, item) => sum + Math.max(0, item.value), 0);
  return <div><div className="distribution-bar" aria-label="Distribución de ingresos">{items.map(item => <span key={item.label} style={{ width: `${total ? Math.max(0, item.value) / total * 100 : 0}%`, backgroundColor: item.color }} />)}</div><div className="distribution-legend">{items.map(item => <span key={item.label}><i style={{ backgroundColor: item.color }} />{item.label} {values.income > 0 ? `${Math.round(Math.max(0, item.value) / values.income * 100)}%` : '—'}</span>)}</div></div>;
}
export function SummaryCard({ values, currency = 'COP', projected = false }: { values: SummaryValues; currency?: string; projected?: boolean }) {
  return <section className={`summary-card ${projected ? 'summary-projected' : ''}`} aria-label={projected ? 'Presupuesto previsto' : 'Resumen financiero'}><p>{projected ? 'Disponible previsto este mes' : 'Disponible este mes'}</p><strong className="available-value" data-testid="available">{formatMoney(values.available, currency)}</strong><div className="summary-grid">{[{ name: 'Ingresos', icon: '↑', value: values.income, color: 'text-emerald-200' }, { name: 'Gastos', icon: '↓', value: values.expenses, color: 'text-rose-200' }, { name: projected ? 'Cuotas previstas' : 'Pagos de deudas', icon: '💳', value: values.debtPayments, color: 'text-amber-200' }, { name: projected ? 'Reserva de ahorro' : 'Ahorro del mes', icon: '🐷', value: values.savings, color: 'text-sky-200' }].map(item => <div key={item.name}><span>{item.icon} {item.name}</span><b className={item.color}>{formatMoney(item.value, currency)}</b></div>)}</div>{!projected && <><p className="text-xs mb-2 opacity-70">Distribución</p><DistributionBar values={values} /></>}</section>;
}
